In [2]:
# Data manipulation
import pandas as pd
import numpy as np

# Machine Learning Model
from sklearn.linear_model import LogisticRegression

# Model Evaluation
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

import warnings
warnings.filterwarnings("ignore")

In [3]:
# Load processed datasets

X_train = pd.read_csv("../data/processed/X_train.csv")
X_test = pd.read_csv("../data/processed/X_test.csv")

y_train = pd.read_csv("../data/processed/y_train.csv")
y_test = pd.read_csv("../data/processed/y_test.csv")

In [4]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (5634, 45)
X_test : (1409, 45)
y_train: (5634, 1)
y_test : (1409, 1)


In [5]:
y_train.head()

,Churn
0,0
1,0
2,0
3,0
4,0


In [6]:
y_train.shape

(5634, 1)

In [7]:
y_train = y_train.squeeze()
y_test = y_test.squeeze()

In [8]:
lr_model = LogisticRegression(
    random_state=42,
    max_iter=1000
)

In [10]:
lr_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [11]:
y_pred = lr_model.predict(X_test)

In [13]:
print(y_pred[:20])

[0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0]


In [14]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8055358410220014


In [15]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[926 109]
 [165 209]]


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.66      0.56      0.60       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409



In [17]:
coefficients = pd.DataFrame({
    "Feature": X_train.columns,
    "Coefficient": lr_model.coef_[0]
})

coefficients.head()

,Feature,Coefficient
0,num__SeniorCitizen,0.053929
1,num__tenure,-1.241319
2,num__MonthlyCharges,-0.596392
3,num__TotalCharges,0.516708
4,cat__gender_Female,-0.167742


In [18]:
coefficients = coefficients.sort_values(
    by="Coefficient",
    ascending=False
)

coefficients

,Feature,Coefficient
16,cat__InternetService_Fiber optic,0.640026
36,cat__Contract_Month-to-month,0.579304
3,num__TotalCharges,0.516708
35,cat__StreamingMovies_Yes,0.204014
32,cat__StreamingTV_Yes,0.203626
43,cat__PaymentMethod_Electronic check,0.198412
18,cat__OnlineSecurity_No,0.157023
27,cat__TechSupport_No,0.132115
14,cat__MultipleLines_Yes,0.105954
0,num__SeniorCitizen,0.053929


In [19]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))

Decision Tree Accuracy: 0.7288857345635202


In [20]:
# Training accuracy
train_pred = dt_model.predict(X_train)

train_accuracy = accuracy_score(y_train, train_pred)

print("Training Accuracy:", train_accuracy)

Training Accuracy: 0.9980475683351083


In [21]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 0.7778566359119943


In [23]:
print("Decision Tree Classification Report")
print(classification_report(y_test, dt_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, dt_pred))

Decision Tree Classification Report
              precision    recall  f1-score   support

           0       0.82      0.81      0.81      1035
           1       0.49      0.51      0.50       374

    accuracy                           0.73      1409
   macro avg       0.65      0.66      0.66      1409
weighted avg       0.73      0.73      0.73      1409


Confusion Matrix
[[838 197]
 [185 189]]


In [24]:
print("Random Forest Classification Report")
print(classification_report(y_test, rf_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, rf_pred))

Random Forest Classification Report
              precision    recall  f1-score   support

           0       0.82      0.89      0.85      1035
           1       0.60      0.48      0.53       374

    accuracy                           0.78      1409
   macro avg       0.71      0.68      0.69      1409
weighted avg       0.77      0.78      0.77      1409


Confusion Matrix
[[918 117]
 [196 178]]


Hyperparameter tuning

In [27]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

dt_depth3 = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt_depth3.fit(X_train, y_train)

train_pred = dt_depth3.predict(X_train)
test_pred = dt_depth3.predict(X_test)

print("Training Accuracy:", accuracy_score(y_train, train_pred))
print("Testing Accuracy :", accuracy_score(y_test, test_pred))

Training Accuracy: 0.80386936457224
Testing Accuracy : 0.7984386089425124


In [ ]:
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.metrics import accuracy_score

# depths = [2, 3, 4, 5, 6, 8, 10]

# print(f"{'Depth':<8}{'Train Acc':<15}{'Test Acc'}")

# for depth in depths:
#     model = DecisionTreeClassifier(
#         max_depth=depth,
#         random_state=42
#     )

#     model.fit(X_train, y_train)

#     train_pred = model.predict(X_train)
#     test_pred = model.predict(X_test)

#     train_acc = accuracy_score(y_train, train_pred)
#     test_acc = accuracy_score(y_test, test_pred)

#     print(f"{depth:<8}{train_acc:.4f}         {test_acc:.4f}")

Depth   Train Acc      Test Acc
2       0.7654         0.7509
3       0.7914         0.7821
4       0.7966         0.7921
5       0.8039         0.7984
6       0.8104         0.7913
8       0.8372         0.7750
10      0.8784         0.7544


In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [29]:
depths = [2, 3, 4, 5, 6, 8, 10]

print(f"{'Depth':<8}{'Train Acc':<15}{'Test Acc'}")

for depth in depths:

    rf = RandomForestClassifier(
        n_estimators=100,
        max_depth=depth,
        random_state=42
    )

    rf.fit(X_train, y_train.values.ravel())

    train_pred = rf.predict(X_train)
    test_pred = rf.predict(X_test)

    train_acc = accuracy_score(y_train, train_pred)
    test_acc = accuracy_score(y_test, test_pred)

    print(f"{depth:<8}{train_acc:.4f}         {test_acc:.4f}")

Depth   Train Acc      Test Acc
2       0.7588         0.7594
3       0.7891         0.7828
4       0.7962         0.7913
5       0.8014         0.7956
6       0.8124         0.8020
8       0.8358         0.8041
10      0.8750         0.8027


In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
param_grid = {
    "n_estimators": [50, 100, 200],
    "max_depth": [4, 6, 8],
    "min_samples_leaf": [1, 2, 4]
}
grid = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)
grid.fit(X_train, y_train.values.ravel())
print("Best Parameters:")
print(grid.best_params_)
print("Best Cross Validation Accuracy:")
print(grid.best_score_)
best_rf = grid.best_estimator_

pred = best_rf.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, pred))
print("\nClassification Report:")
print(classification_report(y_test, pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, pred))

Best Parameters:
{'max_depth': 8, 'min_samples_leaf': 4, 'n_estimators': 100}
Best Cross Validation Accuracy:
0.8049314343082201
Test Accuracy: 0.8069552874378992

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.91      0.87      1035
           1       0.68      0.52      0.59       374

    accuracy                           0.81      1409
   macro avg       0.76      0.72      0.73      1409
weighted avg       0.80      0.81      0.80      1409


Confusion Matrix:
[[942  93]
 [179 195]]


In [31]:
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)
xgb_model.fit(X_train, y_train.values.ravel())
xgb_pred = xgb_model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, xgb_pred))

print("\nClassification Report")
print(classification_report(y_test, xgb_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, xgb_pred))

Accuracy: 0.7735982966643009

Classification Report
              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1035
           1       0.59      0.50      0.54       374

    accuracy                           0.77      1409
   macro avg       0.71      0.69      0.69      1409
weighted avg       0.76      0.77      0.77      1409


Confusion Matrix
[[904 131]
 [188 186]]
